import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <style
            dangerouslySetInnerHTML={{
              __html: `
            ::highlight(MdxSearch) {
              background: rgba(255, 255, 0, 0.4);
            }
            .dark ::highlight(MdxSearch) {
              background: rgba(255, 255, 0, 0.3);
            }
            ::highlight(MdxFocusSearch) {
              background: rgba(255, 100, 0, 0.6);
            }
            .dark ::highlight(MdxFocusSearch) {
              background: rgba(255, 150, 0, 0.5);
            }
          `,
            }}
          />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
