import type { Metadata } from "next";
import { IBM_Plex_Sans, Noto_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { cn } from "@/lib/utils";

const notoSansHeading = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "font-sans",
        ibmPlexSans.variable,
        notoSansHeading.variable,
      )}
    >
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <style>{`
            ::highlight(MdxSearch) {
              background: rgba(255, 255, 0, 0.4);
            }
            .dark ::highlight(MdxSearch) {
              background: rgba(255, 255, 0, 0.3);
            }
            ::highlight(MdxFocusSearch) {
              background: rgba(255, 100, 0, 0.6);
            }
            .dark ::highlight(MdxFocusSearch) {
              background: rgba(255, 150, 0, 0.5);
            }
          `}</style>
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
